name: Reset stage to main

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  reset:
    name: Reset stage branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset stage to main
        run: |
          git fetch origin
          git checkout stage
          git reset --hard origin/main
          git push origin stage --force-with-lease
